Player:
  params:
    - board: Board
  methods:
    - Player()
    - void giveShipLocation(Ship ship)
    - void drawFullBoard()
    - void drawFoggedBoard()
    - void startGame()
    - void fire()
    - Position getPositionFromText(String text)
    - win(): TODO

Position:
  params:
    - row
    - col
    - rowDisplay
    - colDisplay
  methods:
    - boolean equals(Object o)
    - boolean positionInBounds()

Board:
  params:
    - areas: ArrayList<Area>
    - areaOfInfluence: HashSet<Position>
  methods:
    - String getBoardForDisplay(boolean fog)
    - boolean hitOrMiss(Shelling shelling)
    - void processShipPlacement(Ship ship, Position beginning, Position end)
    - void checkAreaOfInfluence(Ship ship)
    - void processShelling(Position coordinates)


Area (Abstract):
  params:
    - positions: ArrayList<Positions>
  methods:
    - void setLocation(Position[] positions): definition

Ship extends Area:
  params:
    - noOfCells: int
    - name: String
    - hitPoints: int
    - areaOfInfluence: HashSet<Positions>
  methods:
    - HashSet<Position> fillAreaOfInfluence(ArrayList<Position> positions)
    - ArrayList<Position> fillShipLocation(int rowMin, int rowMax, int colMin, int colMax)
    - void setLocation(Position[] positions): implementation


Shelling extends Area:
  methods:
    - void setLocation(Position[] positions): implementation
